### ISSUE TITLE
Documentation: hekate_ipl.ini changes

### ISSUE THREAD

**Issue by parkerlreed** [ITotalJustice/patches#10]
Might want to mention that `kip1patch=nosigchk` is needed in the CFW ini section for things to work (at least for hekate)

**Comment by arch-box** [comment]
Good suggestion! I just have the following line in my hekate_ip.ini config and it just werks:

```
[Atmosphere CFW]
payload=bootloader/payloads/fusee-primary.bin
```

I know other hekate patches ZIPs have a heakte_ipl.ini in them, but I am again overwriting anyone's config files. If people want to use the hekate patches and decide to set up their own big-brain fss0 config, they need to make sure they include all the options for whatever it is that they are doing. 

I'm going to add my whole hekate config in the readme or code if anyone wants to use a config that works, but I would suggest people either just boot or chainload the Atmosphere RCM payload unless they really know what they are doing. I usually just stick with that although I do use the following configs to test the other patches. Hekate didn't support FW 11 when the latest es and fs patches were produced, so I had to chainload fusee-primary originally anyways. 

```
[CFW - FSS0 SYS]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
emummc_force_disable=1

[CFW - FSS0 EMU]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
emummcforce=1
```
