### ISSUE TITLE
Mariko Loader patches

### ISSUE THREAD

**Issue by sirthizzalot** [ITotalJustice/patches#11]
Sorry if this isn’t the place to ask. I’m running a modified Hekate and using it to launch AMS on my Mariko. The normal patches work fine, but I’m unable to launch Tinfoil. From my understanding the loader patches are the cause. If I send you my hekate and fusee secondary could you make compatible patches?

**Comment by arch-box** [comment]
no that's illegal

**Comment by arch-box** [comment]
(I also didn't make any of these, these are just copied and pasted from gbatemp, I would check on there or reach out to a hacker)
