### ISSUE TITLE
Tinfoil will not work even with new patches

### ISSUE THREAD

**Issue by pickleboi7** [ITotalJustice/patches#12]
I finally decided to add a CFW to my switch. Everything seems to be working but tinfoil just absolutely refuses to boot no matter what I do. I tried both fusee primary and hentake methods. Both did not work, I am really confused and unsure what to do. I tried to boot it from both emu and sysnand. In both cases, it did not work. I booted it by holding the R button then going into the homebrew menu as well as trying to go through albums. I am unsure what the problem is, I am running the latest firmware on switch and atmosphere

**Comment by arch-box** [comment]
Try using the Tinfoil NSP and install it using a different title installer like tinleaf

**Comment by pickleboi7** [comment]
> 
> 
> Try using the Tinfoil NSP and install it using a different title installer like tinleaf

I ended up using lithium which works on my current version for some reason. I was able to install a smaller .nsp file. The problem is that my micro sd was reformated from exfat to fat32 by the switch or something like that. I am unsure how it changed formats since it wasn't even an option for it on windows for reformating. I tried to split the files and install them as well as XCI files. Both these attempts failed. I ended up downloading nut and am trying to install applications through usb from the computer directly. The first file I tried failed, the 2nd file which I had previous game data has worked. I will now attempt to install another nsp file using this method assuming the old one was corrupted. I will keep you updated and maybe try your method if all else fails, thanks

**Comment by Masamune3210** [comment]
The switch will not reformat your sd card unless you tell it to, so if it changed something changed it. You can format your sd card to fat32 using any number of tools. Windows won't do it by default because it's dumb and thinks limits exist that don't exist

**Comment by pickleboi7** [comment]
> The switch will not reformat your sd card unless you tell it to, so if it changed something changed it. You can format your sd card to fat32 using any number of tools. Windows won't do it by default because it's dumb and thinks limits exist that don't exist

Do you know of a way to bypass the fake 4gb limit windows adds to fat32? My SD is currently formated as fat32

**Comment by Masamune3210** [comment]
http://ridgecrop.co.uk/index.htm?guiformat.htm

**Comment by jcbuzby** [comment]
> 
> 
> I finally decided to add a CFW to my switch. Everything seems to be working but tinfoil just absolutely refuses to boot no matter what I do. I tried both fusee primary and hentake methods. Both did not work, I am really confused and unsure what to do. I tried to boot it from both emu and sysnand. In both cases, it did not work. I booted it by holding the R button then going into the homebrew menu as well as trying to go through albums. I am unsure what the problem is, I am running the latest firmware on switch and atmosphere

Check hekate_ipl.ini file. you prob have the one that only has 2 lines under CFWemmu. you need to add the nosigcheck line

**Comment by pickleboi7** [comment]
Little update. I got it working with lithium using the fusee_primary payload with the Sigpatchs. I install games by accessing them from the pc directory using the "NUT" which allows me connect my switch directly to pc with lithium. I hope everything gets updated so I can use tinfoil. Everything seems to be fine for now. Just for reference I'm on the latest switch firmware and latest firmware for everything, expect jut which I used the 3.5 version I believe

**Comment by arch-box** [comment]
>  I hope everything gets updated so I can use tinfoil.

Tinfoil works fine with these patches, no update is coming. What error message are you getting when you try to install the latest Tinfoil NSP?

**Comment by arch-box** [comment]
> 
> http://ridgecrop.co.uk/index.htm?guiformat.htm

You can just use hekate to format the SD. It will align for performance, and walk you through backing up your data using UMS.

**Comment by pickleboi7** [comment]
> >  I hope everything gets updated so I can use tinfoil.
> 
> Tinfoil works fine with these patches, no update is coming. What error message are you getting when you try to install the latest Tinfoil NSP?
> 
> 

Tinfoil NSP installs but it is unable to start. I'm not the only one having this issue on the latest Horizon firmware. I found a video talking about it online and it suggested to get lithium which I did and it works Atleast. I'm just installing nsp directly from the pc HDD onto the switch due to the Fat32 limitations, thanks though.

**Comment by arch-box** [comment]
> 
> 
> > > I hope everything gets updated so I can use tinfoil.
> > 
> > 
> > Tinfoil works fine with these patches, no update is coming. What error message are you getting when you try to install the latest Tinfoil NSP?
> 
> Tinfoil NSP installs but it is unable to start. I'm not the only one having this issue on the latest Horizon firmware. I found a video talking about it online and it suggested to get lithium which I did and it works Atleast. I'm just installing nsp directly from the pc HDD onto the switch due to the Fat32 limitations, thanks though.

Did you uninstall the current Tinfoil, and now you are installing the latest Tinfoil.nsp using lithum? Are you installing the Tinfoil NSP to your NAND or to SD?

**Comment by pickleboi7** [comment]
> > 
> > 
> > > > I hope everything gets updated so I can use tinfoil.
> > > 
> > > 
> > > Tinfoil works fine with these patches, no update is coming. What error message are you getting when you try to install the latest Tinfoil NSP?
> > 
> > Tinfoil NSP installs but it is unable to start. I'm not the only one having this issue on the latest Horizon firmware. I found a video talking about it online and it suggested to get lithium which I did and it works Atleast. I'm just installing nsp directly from the pc HDD onto the switch due to the Fat32 limitations, thanks though.
> 
> Did you uninstall the current Tinfoil, and now you are installing the latest Tinfoil.nsp using lithum? Are you installing the Tinfoil NSP to your NAND or to SD?

I didn't think tinfoil has a  .nsp option. Tinfoil was installed on my nand unfortunately and I'm unsure how I did that, I deleted that version because it didn't work. I also did install it on micro SD aswell as use the latest Sigpatch first for hekate and then for faseee_primary. In both cases tinfoil would install but would refuse to start when I clicked on it. I suppose I could try installing tinfoil through lithium (light weight version of tinfoil). I'm just scared it might cause some problems when I finally got it working

**Comment by arch-box** [comment]
> 
> 
> > > > > I hope everything gets updated so I can use tinfoil.
> > > > 
> > > > 
> > > > Tinfoil works fine with these patches, no update is coming. What error message are you getting when you try to install the latest Tinfoil NSP?
> > > 
> > > 
> > > Tinfoil NSP installs but it is unable to start. I'm not the only one having this issue on the latest Horizon firmware. I found a video talking about it online and it suggested to get lithium which I did and it works Atleast. I'm just installing nsp directly from the pc HDD onto the switch due to the Fat32 limitations, thanks though.
> > 
> > 
> > Did you uninstall the current Tinfoil, and now you are installing the latest Tinfoil.nsp using lithum? Are you installing the Tinfoil NSP to your NAND or to SD?
> 
> I didn't think tinfoil has a .nsp option. Tinfoil was installed on my nand unfortunately and I'm unsure how I did that, I deleted that version because it didn't work. I also did install it on micro SD aswell as use the latest Sigpatch first for hekate and then for faseee_primary. In both cases tinfoil would install but would refuse to start when I clicked on it. I suppose I could try installing tinfoil through lithium (light weight version of tinfoil). I'm just scared it might cause some problems when I finally got it working

what error messages happens the first time you try running tinfoil? and the 2nd?

tinfoil.io has an NSP version, that's the latest version that you should be installing via lithium. Install it to your NAND when it asks where you want to install it.

**Comment by arch-box** [comment]
Tinfoil is working also on Atmosphere 0.17.0 with the latest sigpatches. I am closing this issue so that people don't read the title and think that Tinfoil won't work with these patches.
