### ISSUE TITLE
fifa 21 doesnt load

### ISSUE THREAD

**Issue by rubensk8er** [ITotalJustice/patches#13]
“the software was closed because an error occurred”  have this problem with all nsps installed on 0.16.2 fw 11.0.1
.

**Comment by arch-box** [comment]
Works on my machine. Did you extract the patches properly, and reboot?

**Comment by eXhumer** [comment]
Bad setup. Patches work with "backup copy" of FIFA 21 for me.

@arch-box Disable issue creation for this project.

**Comment by rubensk8er** [comment]
I have this problem i dont know why, its a known issue too just check for switch-xci.xyz and nx brew. Com there they are getting too i didnt had any problems on 10.2.0 0.15 ams

**Comment by arch-box** [comment]
No piransi

**Comment by arch-box** [comment]
> @arch-box Disable issue creation for this project.

not my project, I can't change any settings :(
