### ISSUE TITLE
Issue Installing with GoldLeaf 

### ISSUE THREAD

**Issue by Ricsesz** [ITotalJustice/patches#2]
Hello!
I have bought a brand new 256gb sd card and installed the necessary files to run my cfw from sdsetup. I am on system version 10.1.0 and Atmosphere 0.15.0. Everything works nice and dandy except when I try to install a nsp I get the following error:
An error occured attempting to install the NSP:
Error: 2145-0001(0x291)
Module:Etickets(145)
Description: Unknown or undocumented error(1).

I have been browsing the internet trying to fix this for hours. I am at the point where I dont know what to do. I have tried to download new sigpatches and I am pretty sure I have the right sigpatches and everything is installed correctly.
Please help me if you can.
Also with another sd card and an older atmosphere setup everything work correctly.

**Comment by arch-box** [comment]
Try downloading the latest fusee.zip patches and inject the latest fusee-primary from the Atmosphere github releases page.

**Comment by arch-box** [comment]
Use updated homebrew apps that support latest firmware.
