### ISSUE TITLE
11.0.0-0.16.0p2 patches.ini missing 11.0.0 FS patches

### ISSUE THREAD

**Issue by pixeltester** [ITotalJustice/patches#5]
per title

**Comment by arch-box** [comment]
Added to hekate.zip

**Comment by arch-box** [comment]
The hekate/fss0 ini patches might not be working for fs on latest, I would suggest using the normal atmosphere payload to boot if it's causing issues, guide to adding fusee-primary to hekate's options: https://birbchirp.gitbook.io/switchguide/cfw-guides/atmosphere/optional-booting-atmosphere-with-hekate

**Comment by arch-box** [comment]
I updated the patches.ini just now with new 11.0.0 FS patches, if any issues were occurring please try redownloading.
