### ISSUE TITLE
There is only loader's patches for 11.0.1-0.16.1

### ISSUE THREAD

**Issue by rashevskyv** [ITotalJustice/patches#6]
So homebrew from main screen and XCI-converts did not works

![изображение](https://user-images.githubusercontent.com/18294541/101981801-15896500-3c78-11eb-8bb5-4dd8675a26bf.png)
![изображение](https://user-images.githubusercontent.com/18294541/101981813-2934cb80-3c78-11eb-9785-4240ffeaa13c.png)
![изображение](https://user-images.githubusercontent.com/18294541/101981821-3a7dd800-3c78-11eb-9e44-3ab6b58bed90.png)

**Comment by arch-box** [comment]
It is working fine on firmware 11.0.0 and 11.0.1 on atmosphere 0.16.1 with both fusee-primary booting and hekate fss0 loading.
