### ISSUE TITLE
Firmware 11.0.1 section missing on patches.ini

### ISSUE THREAD

**Issue by impeeza** [ITotalJustice/patches#7]
Hi on the hekate release of 11.0.1-0.16.1 version, inside the zip file, on the bootloader\patches.ini  file there is not 11.0.1 section therefore the FS .nosigchk patch will be not applied, please add the needed section.   thanks.

**Comment by arch-box** [comment]
`fs` didn't change in 11.0.1

**Comment by impeeza** [comment]
cool, so are the same checksum for both firmwares?  i will put the comment on my own patches.ini.  thanks a lot.

**Comment by arch-box** [comment]
Yes, just like how you don't have separate comments for 10.0.1, 10.0.2, etc.

Please also don't open issues saying the patches won't work, this confuses people even though the latest patches release is working fine on firmware 11.0.0 and 11.0.1 on atmosphere 0.16.1 with both fusee-primary booting and hekate fss0 loading.
