### ISSUE TITLE
Hombrews from main screen do not works 

### ISSUE THREAD

**Issue by rashevskyv** [ITotalJustice/patches#8]
According to switchbrew, the Atmosphere's version has changed, this has changed the hash of modules. so need to rename FS and ES patches

**Comment by arch-box** [comment]
FS and ES patches do not patch Atmosphere.

**Comment by arch-box** [comment]
I'm able to launch Tinfoil and the homebrew sm64 port from home screen. It is working fine on firmware 11.0.0 and 11.0.1 on atmosphere 0.16.1 with both fusee-primary booting and hekate fss0 loading.
