### ISSUE TITLE
Atmosphere silent update requires new loader patches

### ISSUE THREAD

**Issue by fennectech** [ITotalJustice/patches#9]
new loader patches needed

**Comment by tehfrag** [comment]
Bulid with hash "-1ec2c0c2" in the .zip release name should work with with: https://github.com/ITotalJustice/patches

**Comment by fennectech** [comment]
Indeed it does.  BUT.  I explicitly updated to fix the web applet bug.

**Comment by tehfrag** [comment]
You really should not be under any CFW and accessing the eShop. Use EmuNAND for Atmosphere & SYSNAND for eShop usage.

**Comment by fennectech** [comment]
Heh.  Ive been running atmosphere since before hekate had exfat support and ive been online entirely since then.    Nintendo **KNOWS** i have cfw on my switch.   They just dont seem to care.     The safety ship has already sailed in 2017 and and there is no point to emunand for me.    Nintendo has been letting me have fun with retroarch and stuff and I am thanking them by continuing to buy stuff in the eshop.

**Comment by arch-box** [comment]
This silent update? 
> Note: The 0.16.0 pre-release builds were updated on 2020/12/11 at 5 AM PST to fix a bug that caused the web browser to not work when using mesosphere. The updated zip has a build hash of "-1ec2c0c2".

Please see the release notes from 6 days ago here:

> includes fusee and hekate loader patches for AMS 0.16.1 pre-release, the zip has a build hash of "-1ec2c0c2"

Not seeing any issue here.

**Comment by fennectech** [comment]
Haha i  nosigchk had gotten eaten somehow in the process of updating       Im dumb

**Comment by arch-box** [comment]
It is ok--these things happen 😸 it was suggested I include a note about using that if you decide to to chainload or boot with fusee-primary.bin, I will add some more documentation: https://github.com/ITotalJustice/patches/issues/10
